On Html Page Create Training
Choice Auswahltest as you press add you will receive an Error 
Auswahltest leads to this Traceback :
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1469, in dispatch_request  
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\code\Uni\Projektstudium-Sensorik\Flask\app.py", line 341, in create_training
    return render_template('create_training.html', form=form)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\templating.py", line 132, in _render     
    rv = template.render(context)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jinja2\environment.py", line 1301, in render   
    self.environment.handle_exception()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\code\Uni\Projektstudium-Sensorik\Flask\templates\create_training.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\code\Uni\Projektstudium-Sensorik\Flask\templates\base.html", line 25, in top-level template code
    {% block content %}{% endblock %}
  File "c:\code\Uni\Projektstudium-Sensorik\Flask\templates\create_training.html", line 59, in block 'content'
    {{question.proben_id.label(class="form-label")}}
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jinja2\environment.py", line 485, in getattr   
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtforms.fields.form.FormField object' has no attribute 'proben_id'
